### ISSUE TITLE
FileNotFoundException occurs when executing JavaParser.parse.

### ISSUE THREAD

**Issue by densan-razuma** [paulirwin/JavaToCSharp#27]
![image](https://user-images.githubusercontent.com/65328235/124616883-6c26ec80-deb1-11eb-8e61-145c67f09c70.png)

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'com.github.javaparser.JavaParser' threw an exception.
  Source=javaparser-core-3.0.0-SNAPSHOT
  スタック トレース:
   at com.github.javaparser.JavaParser.parse(InputStream in)
   at JavaToCSharp.JavaToCSharpConverter.ConvertText(String javaText, JavaConversionOptions options) in C:\Users\razuma\Documents\Visual Studio 2019\Projects\JavaToCSharp\JavaToCSharp\JavaToCSharpConverter.cs:line 32
   at JavaToCSharpCli.Program.Main(String[] args) in C:\Users\razuma\Documents\Visual Studio 2019\Projects\JavaToCSharp\JavaToCSharpCli\Program.cs:line 28

内部例外 1:
TypeInitializationException: The type initializer for 'java.nio.charset.Charset' threw an exception.

内部例外 2:
TypeInitializationException: The type initializer for 'sun.misc.VM' threw an exception.

内部例外 3:
TypeInitializationException: The type initializer for 'java.lang.Props' threw an exception.

内部例外 4:
FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. 指定されたファイルが見つかりません。

```

**Comment by paulirwin** [comment]
@densan-razuma Thanks for the bug report. Can I ask how you're using the code - the GUI, CLI, or NuGet package?

**Comment by densan-razuma** [comment]
Occurs when running in the CLI.

In NuGet, I solved it by adding Caliburn.Micro and setting the TargetFramework to net5.0-windows.

JavaToCSharpCli.csproj
```csproj
  <PropertyGroup>
    <Version>2.0.0</Version>
    <OutputType>Exe</OutputType>
-    <TargetFramework>net5.0</TargetFramework>
+    <TargetFramework>net5.0-windows</TargetFramework>
  </PropertyGroup>
+  <ItemGroup>
+    <PackageReference Include="Caliburn.Micro" Version="4.0.173" />
+  </ItemGroup>
```

**Comment by paulirwin** [comment]
Interesting, I'll look into that. Caliburn should only be required by the GUI app.

**Comment by paulirwin** [comment]
Hi @densan-razuma, this has been fixed for both the CLI project as well as the NuGet package. Only change needed was adding a reference to System.Configuration.ConfigurationManager for IKVM. Thanks for reporting this! I mainly use the GUI app so I had neglected the CLI as part of the .NET 5 upgrade.

**Comment by densan-razuma** [comment]
Thank you for fix!!!
